#Compiler
CC = clang++

#Subdirectories
DE = databaseEngine
HS = httpServer
JS = jsonImplementation
CP = configPackage
TS = tests

#Compiler flags
CPPFLAGS = -std=c++11 -Wall -c -g -I$(HS) -I$(DE) -I$(JS) -I$(CP)

#Object files
OBJ = database.o command_facade.o table.o server.o command.o insert_PK_Command.o\
make_table_command.o create_command.o set_table_command.o insert_command.o\
get_command.o get_all_command.o delete_command.o update_command.o sum_command.o\
transaction_commands.o condition_command.o in_command.o request_obj.o\
json_elements.o json_list.o json_value.o json_object.o config_singleton.o

#Test object files
TS_OBJ = engineTests.o testRunner.o

output: $(OBJ) main.o
	$(CC) -o SiMDB.exe $(OBJ) main.o

database.o: $(DE)/database.h $(DE)/database.cpp 
	$(CC) $(CPPFLAGS) $(DE)/database.cpp

table.o: $(DE)/table.h $(DE)/table.cpp
	$(CC) $(CPPFLAGS) $(DE)/table.cpp

server.o: $(HS)/server.h $(HS)/server.cpp
	$(CC) $(CPPFLAGS) $(HS)/server.cpp

command.o: $(DE)/commands.h $(DE)/command.cpp
	$(CC) $(CPPFLAGS) $(DE)/command.cpp

make_table_command.o: $(DE)/commands.h $(DE)/make_table_command.cpp
	$(CC) $(CPPFLAGS) $(DE)/make_table_command.cpp

create_command.o: $(DE)/commands.h $(DE)/create_command.cpp
	$(CC) $(CPPFLAGS) $(DE)/create_command.cpp

set_table_command.o: $(DE)/commands.h $(DE)/set_table_command.cpp
	$(CC) $(CPPFLAGS) $(DE)/set_table_command.cpp

insert_PK_Command.o: $(DE)/commands.h $(DE)/insert_PK_command.cpp
	$(CC) $(CPPFLAGS) $(DE)/insert_PK_command.cpp

insert_command.o: $(DE)/commands.h $(DE)/insert_command.cpp
	$(CC) $(CPPFLAGS) $(DE)/insert_command.cpp

command_facade.o: $(DE)/command_facade.h $(DE)/command_facade.cpp
	$(CC) $(CPPFLAGS) $(DE)/command_facade.cpp

get_command.o: $(DE)/commands.h $(DE)/get_command.cpp
	$(CC) $(CPPFLAGS) $(DE)/get_command.cpp

get_all_command.o: $(DE)/commands.h $(DE)/get_all_command.cpp
	$(CC) $(CPPFLAGS) $(DE)/get_all_command.cpp

delete_command.o: $(DE)/commands.h $(DE)/delete_command.cpp
	$(CC) $(CPPFLAGS) $(DE)/delete_command.cpp

update_command.o: $(DE)/commands.h $(DE)/update_command.cpp
	$(CC) $(CPPFLAGS) $(DE)/update_command.cpp

transaction_commands.o: $(DE)/commands.h $(DE)/transaction_commands.cpp
	$(CC) $(CPPFLAGS) $(DE)/transaction_commands.cpp

condition_command.o: $(DE)/commands.h $(DE)/condition_command.cpp
	$(CC) $(CPPFLAGS) $(DE)/condition_command.cpp

in_command.o: $(DE)/commands.h $(DE)/in_command.cpp
	$(CC) $(CPPFLAGS) $(DE)/in_command.cpp

sum_command.o: $(DE)/commands.h $(DE)/sum_command.cpp
	$(CC) $(CPPFLAGS) $(DE)/sum_command.cpp

request_obj.o: $(HS)/request_obj.h $(HS)/request_obj.cpp
	$(CC) $(CPPFLAGS) $(HS)/request_obj.cpp

json_elements.o: $(JS)/JSON_elements.h $(JS)/JSON_elements.cpp
	$(CC) $(CPPFLAGS) $(JS)/JSON_elements.cpp

json_list.o: $(JS)/JSON_elements.h $(JS)/JSON_list.cpp
	$(CC) $(CPPFLAGS) $(JS)/JSON_list.cpp

json_object.o: $(JS)/JSON_elements.h $(JS)/JSON_object.cpp
	$(CC) $(CPPFLAGS) $(JS)/JSON_object.cpp

json_value.o: $(JS)/JSON_elements.h $(JS)/JSON_value.cpp
	$(CC) $(CPPFLAGS) $(JS)/JSON_value.cpp

config_singleton.o: $(CP)/config_singleton.h $(CP)/config_singleton.cpp
	$(CC) $(CPPFLAGS) $(CP)/config_singleton.cpp

main.o: $(DE)/main.cpp
	$(CC) $(CPPFLAGS) $(DE)/main.cpp

runTests: $(OBJ) $(TS_OBJ) 
	$(CC) -o tests.exe $(OBJ) $(TS_OBJ)

engineTests.o: $(TS)/engineTests.h $(TS)/engineTests.cpp
	$(CC) $(CPPFLAGS) $(TS)/engineTests.cpp

testRunner.o: $(TS)/testRunner.cpp
	$(CC) $(CPPFLAGS) $(TS)/testRunner.cpp

clean:
	rm *.o
