#Compiler
CC = clang++

#Compiler flags
CPPFLAGS = -std=c++11 -Wall -c -g

#Object files
OBJ = database.o command_facade.o table.o server.o command.o insert_PK_Command.o\
make_table_command.o create_command.o set_table_command.o insert_command.o\
get_command.o get_all_command.o delete_command.o update_command.o sum_command.o\
transaction_commands.o condition_command.o in_command.o request_obj.o main.o\
json_elements.o json_list.o json_value.o json_object.o

output: $(OBJ)
	$(CC) $(OBJ)

database.o: database.h database.cpp
	$(CC) $(CPPFLAGS) database.cpp

table.o: table.h table.cpp
	$(CC) $(CPPFLAGS) table.cpp

server.o: server.h server.cpp
	$(CC) $(CPPFLAGS) server.cpp

command.o: commands.h command.cpp
	$(CC) $(CPPFLAGS) command.cpp

make_table_command.o: commands.h make_table_command.cpp
	$(CC) $(CPPFLAGS) make_table_command.cpp

create_command.o: commands.h create_command.cpp
	$(CC) $(CPPFLAGS) create_command.cpp

set_table_command.o: commands.h set_table_command.cpp
	$(CC) $(CPPFLAGS) set_table_command.cpp

insert_PK_Command.o: commands.h insert_PK_command.cpp
	$(CC) $(CPPFLAGS) insert_PK_command.cpp

insert_command.o: commands.h insert_command.cpp
	$(CC) $(CPPFLAGS) insert_command.cpp

command_facade.o: command_facade.h command_facade.cpp
	$(CC) $(CPPFLAGS) command_facade.cpp

get_command.o: commands.h get_command.cpp
	$(CC) $(CPPFLAGS) get_command.cpp

get_all_command.o: commands.h get_all_command.cpp
	$(CC) $(CPPFLAGS) get_all_command.cpp

delete_command.o: commands.h delete_command.cpp
	$(CC) $(CPPFLAGS) delete_command.cpp

update_command.o: commands.h update_command.cpp
	$(CC) $(CPPFLAGS) update_command.cpp

transaction_commands.o: commands.h transaction_commands.cpp
	$(CC) $(CPPFLAGS) transaction_commands.cpp

condition_command.o: commands.h condition_command.cpp
	$(CC) $(CPPFLAGS) condition_command.cpp

in_command.o: commands.h in_command.cpp
	$(CC) $(CPPFLAGS) in_command.cpp

sum_command.o: commands.h sum_command.cpp
	$(CC) $(CPPFLAGS) sum_command.cpp

request_obj.o: request_obj.h request_obj.cpp
	$(CC) $(CPPFLAGS) request_obj.cpp

json_elements.o: JSON_elements.h JSON_elements.cpp
	$(CC) $(CPPFLAGS) JSON_elements.cpp

json_list.o: JSON_elements.h JSON_list.cpp
	$(CC) $(CPPFLAGS) JSON_list.cpp

json_object.o: JSON_elements.h JSON_object.cpp
	$(CC) $(CPPFLAGS) JSON_object.cpp

json_value.o: JSON_elements.h JSON_value.cpp
	$(CC) $(CPPFLAGS) JSON_value.cpp

main.o: main.cpp
	$(CC) $(CPPFLAGS) main.cpp

clean:
	rm *.o
